sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  

matrix:
  include:
  
  - ghc: 8.0.1
    env: GHCVER='8.0.1' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.1
        - cabal-install-head
  
  - ghc: 8.0.2
    env: GHCVER='8.0.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.2
        - cabal-install-head
  
  - ghc: 8.2.2
    env: GHCVER='8.2.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.2.2
        - cabal-install-head
  
  - ghc: 8.4.3
    env: GHCVER='8.4.3' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.3
        - cabal-install-head
  
  - ghc: 8.4.4
    env: GHCVER='8.4.4' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - cabal-install-head
  

install:
  - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - echo $PATH
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test

notifications:
  email: false
